### ISSUE TITLE
xsampe~library not compilable with current flext with Max 7 SDK for 64 bit

### ISSUE THREAD

**Issue by ghost** [grrrr/xsample#2]
I'm trying to compile the xsample objects for Max 7 64bit with the latest flext, but I'm failing, because the nex main signaure is not supported, any ideas?
thx

/*j

**Comment by grrrr** [comment]
Hi Jan, do want to compile it for 64-bit DSP? This is currently not supported in the main branch, but there is a respective pull request. The thing with "nex main signature" i don't get.

**Comment by ghost** [comment]
Hello Thomas,

Sorry for being unclear, the new SDK changes the main function signature as well as the 64bit dsp and perform routines. They're much simpler and clearer now, but above all much different from before and certainly from PD.

```
void myobj_dsp64(t_myobj *x, t_object *dsp64, short *count, double samplerate, long maxvectorsize, long flags);

void myobj_perform64(t_myobj *x, t_object *dsp64, double **ins, long numins, double **outs, long numouts, long sampleframes, long flags, void ``*userparam);
```

In addition the main datatypes have changed to include 64bit variables:

```
/** A float -- always a 32 bit floating point number.       @ingroup msp    */
typedef float t_float;

/** A double -- always a 64 bit floating point number.      @ingroup msp    */
typedef double t_double;

/** A sample value -- width determined by MSP version.      @ingroup msp    */
#if MSP64
typedef double t_sample; 
#else
typedef float t_sample;
#endif`
```

So, that implies big changes in flext, I guess....

**Comment by grrrr** [comment]
Hi,
the datatype changes are fully recognized by flext.
The 64 bit dsp chain is implemented by the "64bit mod" pull request, but i am still unsure what is the best way to integrate it.

**Comment by grrrr** [comment]
Actually, i think this has been resolved a while ago. @j45ch, do you like to check?

**Comment by grrrr** [comment]
64-bit DSP with Max is now enabled with [flext commit fa8bde0](https://github.com/grrrr/flext/commit/fa8bde0268a5cb3292feba693fe0c394e0770308) although i consider it still experimental
