### ISSUE TITLE
Max 8 support?

### ISSUE THREAD

**Issue by hectorC** [grrrr/xsample#4]
I'm trying to use an older patch that used xsample. Is there a chance this will be built for Max 8 (Windows)? I've tried to compile it from source but flext fails to build (seems that the structure of the Max SDK changed?).

**Comment by grrrr** [comment]
Hi, externals running under Max 8 could be compiled with an older SDK version unless Max-8-specific features need to be used.
Have you tried the older xsample binary on your system?
Apart from that, i have compiled flext externals with the Max 8 SDK, just not for Windows. Since i don't own a Windows machine, i could only like into a linux-based system (mingw or so) and try to compile there. Not sure though when i could do that.

**Comment by hectorC** [comment]
Thanks for the quick reply. I tried using the old binary from your site but they are 32 bit and Max 8 is 64 bit only, so Max doesn't load them. Can flext and xsample be easily compiled for x64?

**Comment by hectorC** [comment]
After digging a bit more (and reading the flext issues on GitHub) it seems that building flext for x64 requires an amount of work that I can't afford right now. The reason I want to use xgroove~ is because it seems to be the only object I could find that reliably does loop crossfade at variable sizes and allowing direction reversal. It's a bit painful to get that working with vanilla MaxMSP objects. I'll try to analyze your code for xgroove~ and see if I can repurpose it in a vanilla Max object without the flext dependency. Does that sound possible?

Thanks!

**Comment by grrrr** [comment]
Hi, i am looking into it.
It should be possible to compile the external with mingw under linux. Will come back to this when i have succeeded.
best, Thomas

**Comment by grrrr** [comment]
Hi, i succeeded in cross-compiling a xsample.mxe64 external but lacking a Windows machine, can’t run it.
I would like to ask you to try out this Max package: https://owncloud.grrrr.org/index.php/s/zLGdcSfjyCMYNf1
Unzip it to the Max8/packages folder and let me know whether xgroove~ works as expected.

**Comment by hectorC** [comment]
Amazing! Thank you so much. It works so far! At least xgroove~ but I played a bit with the help patches for the other objects and they seemed to work. Very appreciated!
